Q 1] create a numpy array starting from 2 till 50 with a stepsize of 3

In [4]:
# ANS
import numpy as np
print(np.arange(2,50,3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


Q 2] Accept two list of5 elements each from the user.convert them to numpy arrays.concatenate these arrays and print it.

In [1]:
#ANS
import numpy 
First_list = int(input("Enter the size of list "))
print("\n")
numList_1 = list(int(num) for num in input("Enter the list numbers separated by space ").strip().split())[:First_list]
print("First List: ", numList_1)
print("\n")
Second_list = int(input("Enter the size of list "))
print("\n")
numList_2 = list(int(num) for num in input("Enter the list numbers separated by space ").strip().split())[:Second_list]
print("Second List: ", numList_2)
print("\n")
Array_1 = numpy.array(numList_1)
Array_2 = numpy.array(numList_2)

print("Array1 as Numpy_Array ",Array_1)
print("Array2 as Numpy_Array ",Array_2)
print("\n")

Concatenated_array = numpy.concatenate((Array_1, Array_2), axis=0)
print("Concatenated array ", Concatenated_array)
print("\n")
Concatenated_array.sort()
print("Sorted Array ", Concatenated_array)



Enter the size of list 5


Enter the list numbers separated by space 10 2 56 7 8
First List:  [10, 2, 56, 7, 8]


Enter the size of list 5


Enter the list numbers separated by space 24 45 78 90 12
Second List:  [24, 45, 78, 90, 12]


Array1 as Numpy_Array  [10  2 56  7  8]
Array2 as Numpy_Array  [24 45 78 90 12]


Concatenated array  [10  2 56  7  8 24 45 78 90 12]


Sorted Array  [ 2  7  8 10 12 24 45 56 78 90]


Q 3]Write a code snippet to find the dimensions of a ndarry and its size

In [1]:
#ANS
import numpy as np
arr2D = np.array([[10,12,15,17], [18,19,20,21], [22,23,24,25]])
print('2D Numpy Array')
print(arr2D)
print("\n")
numOfRows = np.size(arr2D, 0)
numOfColumns = np.size(arr2D, 1)
print('Number of Rows : ', numOfRows)
print('Number of Columns : ', numOfColumns)

2D Numpy Array
[[10 12 15 17]
 [18 19 20 21]
 [22 23 24 25]]


Number of Rows :  3
Number of Columns :  4


Q 4] How to convert a 1D array into a 2D array? Dmonstrate with help of a code snippet

In [4]:
# ANS
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)
print("\n")

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_2d = np.reshape(arr, (2, 5))
print("2D Array ")
print(arr_2d)


1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]


2D Array 
[[0 1 2 3 4]
 [5 6 7 8 9]]


Q 5]consider two square numpy arrays.stack them vertically and horizentally

In [5]:
#AN
import numpy as np
a= np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
print("Vertical stacking:\n", np.vstack((a, b))) 
  
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


Q 6] How to get unique items and count of unique items?

In [6]:
#ANS
def unique(list1): 
    x = np.array(list1) 
    print(np.unique(x)) 
      
list1 = [10, 20, 10, 30, 40, 40] 
print("The unique values from 1st list is") 
unique(list1) 
  
new_set = set(list1) 
print("No of unique items in the list are:", len(new_set))

The unique values from 1st list is
[10 20 30 40]
No of unique items in the list are: 4
